config/routes.rb
Spree::Core::Engine.routes.append do
  namespace :admin do
    resources :products do
      get :discount_price, :on => :member
      put :put_on_sale, :on => :member
    end
    resources :variants do
      put :put_on_sale, :on => :member
    end
  end
  #namespace :admin do
    #resources :products do
      #post :put_on_sale
    #end
  #end
end

app/views/spree/admin/variants/discount_price.html.erb
<%= render 'spree/admin/shared/product_sub_menu' %>
<%= render :partial => 'spree/admin/shared/product_tabs', :locals => {:current => "Discount Pricing"} %>
<%= render "spree/shared/error_messages", :target => @variant %>

<%= form_for(@variant, :url => admin_product_variant_url(@product, @variant), :html => { :method => :put }) do |f| %>
  <h3><%= Spree.t("discount prices") %></h3>
  <%= f.fields_for :discount_price do |discount_form| %>
    <%= discount_form.label :discount_type %><br/>
    <%= discount_form.select :discount_type, [['Dollar Price', 'price'],['Percent Discount', 'percent'],['Dollar Discount','discount']] %><br/>
    <%= discount_form.label :amount %><br/>
    <%= discount_form.text_field :amount %><br/>

    <% if discount_form.blank? %>
      <span class="price selling">No discount applied yet</span>
    <% else %>
      <span class="price was">Before Discount: <%= product_price(@variant) %></span></br>
      <span class="price now">After Discount: <%= product_price(@variant, :show_calculated_price => true) %></span>
    <% end %>
  <% end %>
  <%= render 'spree/admin/shared/edit_resource_links' %>
<% end %>